# Generated by Django 3.2.24 on 2024-02-28 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('item_desc', models.CharField(max_length=200)),
                ('item_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item_img', models.ImageField(default='img/food_img.jpg', upload_to='')),
            ],
        ),
    ]
